stages:
  
  Training:
    cmd: python fraud_svm.py
    
    deps:
      - fraud_svm.py
      - Data/creditcard.csv
      

    outs:
      - Models/Fraud_SVM.pkl
      - Output/x_test.csv
      - Output/y_test.csv
    

   
  Testing:
    cmd: python fraud_svm_test.py 

    deps:
      - fraud_svm_test.py 
      - Output/x_test.csv
      - Output/y_test.csv
      - Models/Fraud_SVM.pkl
    
    outs:
      
      - Output/Accuracy.json
      - Output/Confusion_matrix.json


